<a href="https://colab.research.google.com/github/Narabcs/doctorship/blob/main/trabalho_nara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


### Etapa 01:

Calculando os valores de tortuosidade utilizando os dados da Ã¡gua
---

In [ ]:
import pandas as pd

dados = pd.read_excel('parametros.xlsx',sheet_name='Water')
dados['y_ress'] = dados['yexp']/dados['xexp']
dados

            yexp        mi      xexp      pf  meio        y_ress
0   3.149606e+07  0.000891  0.008000  997.05    50  3.936980e+09
1   6.299213e+07  0.000891  0.012548  997.05    50  5.020117e+09
2   9.448819e+07  0.000891  0.014814  997.05    50  6.378270e+09
3   1.259843e+08  0.000891  0.017320  997.05    50  7.273944e+09
4   1.574803e+08  0.000891  0.019332  997.05    50  8.146106e+09
5   1.889764e+08  0.000891  0.020579  997.05    50  9.183094e+09
6   2.204724e+08  0.000891  0.022354  997.05    50  9.862864e+09
7   1.574803e+07  0.000891  0.007266  997.05   120  2.167237e+09
8   3.149606e+07  0.000891  0.010599  997.05   120  2.971621e+09
9   6.299213e+07  0.000891  0.014565  997.05   120  4.324781e+09
10  9.448819e+07  0.000891  0.017891  997.05   120  5.281337e+09
11  1.259843e+08  0.000891  0.020982  997.05   120  6.004531e+09
12  1.574803e+08  0.000891  0.024042  997.05   120  6.550249e+09

In [ ]:
from scipy import stats

ress_50 = stats.linregress(x=dados.query('meio==50')['xexp'],y=dados.query('meio==50')['y_ress'])
ress_120 = stats.linregress(x=dados.query('meio==120')['xexp'],y=dados.query('meio==120')['y_ress'])

results = {'meio=50':{'r_squared':ress_50.rvalue,
           'intercept': ress_50.intercept,
           'slope': ress_50.slope},
           'meio=120':{'r_squared':ress_120.rvalue,
           'intercept': ress_120.intercept,
           'slope': ress_120.slope}
           }

results = pd.DataFrame(results)
results

                meio=50      meio=120
r_squared  9.892291e-01  9.957601e-01
intercept  1.089580e+08  2.405323e+08
slope      4.266217e+11  2.711891e+11

In [ ]:
def tortuosity(slope,k,pf):
  c = slope*k**0.5/pf

  return c

In [ ]:
c_50 = tortuosity(results['meio=50'].slope,1.48e-11,dados['pf'].unique())
c_120 = tortuosity(results['meio=120'].slope,3.95e-11,dados['pf'].unique())
print(f'c_50 = {float(c_50)}, c_120 = {float(c_120)}')

c_50 = 1646.1022865725324, c_120 = 1709.440209687404

### Etapa 02: 

Estimando os valores de K para as equaÃ§Ãµes de Forchheimmer e Darcy.

In [ ]:
dados_estimacao = pd.read_excel('parametros.xlsx',sheet_name='OnlyXG')
dados_estimacao

            yexp         m         n      xexp  ...         pf   gx  meio     c
0   3.149606e+07  0.774345  0.325880  0.003056  ...  998.27818  0.2    50  1646
1   6.299213e+07  0.783775  0.321005  0.007027  ...  998.27818  0.2    50  1646
2   9.448819e+07  0.762060  0.325335  0.010319  ...  998.27818  0.2    50  1646
3   1.259843e+08  0.766675  0.321870  0.011798  ...  998.27818  0.2    50  1646
4   1.574803e+08  0.771190  0.316790  0.014499  ...  998.27818  0.2    50  1646
5   1.889764e+08  0.772565  0.313290  0.016343  ...  998.27818  0.2    50  1646
6   2.204724e+08  0.762900  0.315805  0.018316  ...  998.27818  0.2    50  1646
7   3.149606e+07  0.864565  0.320220  0.006275  ...  998.27818  0.2   120  1709
8   6.299213e+07  0.834590  0.314865  0.010121  ...  998.27818  0.2   120  1709
9   9.448819e+07  0.809455  0.314420  0.013199  ...  998.27818  0.2   120  1709
10  1.259843e+08  0.764080  0.320950  0.015305  ...  998.27818  0.2   120  1709
11  1.574803e+08  0.746530  0.315280  0.017404  ...  998.27818  0.2   120  1709
12  1.889764e+08  0.727820  0.320014  0.019983  ...  998.27818  0.2   120  1709
13  2.204724e+08  0.734835  0.318170  0.021439  ...  998.27818  0.2   120  1709
14  3.149606e+07  3.405460  0.208075  0.000610  ...  999.73000  0.4    50  1646
15  6.299213e+07  3.534105  0.207580  0.005357  ...  999.73000  0.4    50  1646
16  9.448819e+07  3.420180  0.214485  0.008815  ...  999.73000  0.4    50  1646
17  1.259843e+08  3.432765  0.213410  0.011457  ...  999.73000  0.4    50  1646
18  1.574803e+08  3.491325  0.206055  0.014022  ...  999.73000  0.4    50  1646
19  1.889764e+08  3.380950  0.211170  0.015856  ...  999.73000  0.4    50  1646
20  2.204724e+08  3.394020  0.207745  0.018061  ...  999.73000  0.4    50  1646
21  3.149606e+07  3.680560  0.205415  0.006091  ...  999.73000  0.4   120  1709
22  6.299213e+07  3.595200  0.214660  0.008909  ...  999.73000  0.4   120  1709
23  9.448819e+07  3.801090  0.201370  0.011932  ...  999.73000  0.4   120  1709
24  1.259843e+08  3.451335  0.206435  0.015568  ...  999.73000  0.4   120  1709
25  1.574803e+08  3.413125  0.205525  0.017830  ...  999.73000  0.4   120  1709
26  1.889764e+08  3.370100  0.208610  0.019822  ...  999.73000  0.4   120  1709
27  2.204724e+08  3.393215  0.208570  0.021336  ...  999.73000  0.4   120  1709

[28 rows x 9 columns]

In [ ]:
def forch_opt(x, dados):
  forch = (dados[1] * ((1.1/(2.5*dados[4])**0.5) * dados[3]/x[0]**0.5)**(dados[2]-1))/x[0] * dados[3] + dados[6]*dados[5]/x[0]**0.5 * dados[3]**2
  err_rel = abs(dados[0] - forch) / dados[0] 

  return err_rel

def darcy_opt(k, dados):
  darcy = (dados[1] * ((1.1/(2.5*dados[4])**0.5) * dados[3]/k**0.5)**(dados[2]-1))/k * dados[3]
  err_rel = abs(dados[0] - darcy) / dados[0] 
  return err_rel

def modelo(dados, model:str='forch'):
  
  if model == 'forch':
    mu = (dados['m'] * ((1.1/(2.5*dados['es'])**0.5) * dados['xexp']/dados['k_forch']**0.5)**(dados['n']-1))
    y = mu/dados['k_forch'] * dados['xexp'] + dados['c']*dados['pf']/dados['k_forch']**0.5 * dados['xexp']**2

  if model == 'darcy':
    mu = (dados['m'] * ((1.1/(2.5*dados['es'])**0.5) * dados['xexp']/dados['k_darcy']**0.5)**(dados['n']-1))
    y = mu/dados['k_darcy'] * dados['xexp']

  return y, mu

In [ ]:
from scipy.optimize import differential_evolution as de

params_bound = [(1e-20,1e-10)]

results = []

for row in dados_estimacao.iterrows():
  dados_selecionados = [row[1]['yexp'], row[1]['m'], row[1]['n'], row[1]['xexp'], row[1]['es'], row[1]['pf'], row[1]['c']]
  value = de(func=forch_opt,bounds=params_bound,args=(dados_selecionados,))
  results.append(value)

df_forch = pd.DataFrame(results)

k_bound = [(1e-20,1e-10)]

results = []

for row in dados_estimacao.iterrows():
  dados_selecionados = [row[1]['yexp'], row[1]['m'], row[1]['n'], row[1]['xexp'], row[1]['es'], row[1]['pf'], row[1]['c']]
  value = de(func=darcy_opt,bounds=k_bound,args=(dados_selecionados,))
  results.append(value)

df_darcy = pd.DataFrame(results)

In [ ]:
k_forch = []
k_darcy = []

for item in zip(df_forch.x,df_darcy.x):
  k_forch.append(item[0][0])
  k_darcy.append(item[1][0])
dados_estimacao['k_forch'] = k_forch
dados_estimacao['k_darcy'] = k_darcy
dados_estimacao['dpl_forch'], dados_estimacao['mu_forch'] = modelo(dados_estimacao,model='forch')
dados_estimacao['dpl_darcy'], dados_estimacao['mu_darcy'] = modelo(dados_estimacao,model='darcy')
dados_estimacao

            yexp         m         n  ...  mu_forch     dpl_darcy  mu_darcy
0   3.149606e+07  0.774345  0.325880  ...  0.002707  3.149606e+07  0.001697
1   6.299213e+07  0.783775  0.321005  ...  0.002225  6.299213e+07  0.000738
2   9.448819e+07  0.762060  0.325335  ...  0.002123  9.448819e+07  0.000506
3   1.259843e+08  0.766675  0.321870  ...  0.001851  5.216888e+06  0.001990
4   1.574803e+08  0.771190  0.316790  ...  0.001738  1.574803e+08  0.000288
5   1.889764e+08  0.772565  0.313290  ...  0.001609  1.889764e+08  0.000232
6   2.204724e+08  0.762900  0.315805  ...  0.001577  2.204724e+08  0.000207
7   3.149606e+07  0.864565  0.320220  ...  0.003321  3.149606e+07  0.001086
8   6.299213e+07  0.834590  0.314865  ...  0.002520  6.299213e+07  0.000516
9   9.448819e+07  0.809455  0.314420  ...  0.002183  9.448819e+07  0.000345
10  1.259843e+08  0.764080  0.320950  ...  0.001974  1.259843e+08  0.000282
11  1.574803e+08  0.746530  0.315280  ...  0.001713  1.574803e+08  0.000205
12  1.889764e+08  0.727820  0.320014  ...  0.001686  5.801713e+06  0.001098
13  2.204724e+08  0.734835  0.318170  ...  0.001580  2.204724e+08  0.000159
14  3.149606e+07  3.405460  0.208075  ...  0.009924  3.149606e+07  0.009640
15  6.299213e+07  3.534105  0.207580  ...  0.003578  6.299213e+07  0.001553
16  9.448819e+07  3.420180  0.214485  ...  0.003411  9.448819e+07  0.000917
17  1.259843e+08  3.432765  0.213410  ...  0.003185  1.259843e+08  0.000634
18  1.574803e+08  3.491325  0.206055  ...  0.002914  1.574803e+08  0.000431
19  1.889764e+08  3.380950  0.211170  ...  0.002795  1.889764e+08  0.000369
20  2.204724e+08  3.394020  0.207745  ...  0.002646  2.204724e+08  0.000289
21  3.149606e+07  3.680560  0.205415  ...  0.005764  3.149606e+07  0.001885
22  6.299213e+07  3.595200  0.214660  ...  0.004427  6.299213e+07  0.001048
23  9.448819e+07  3.801090  0.201370  ...  0.003667  9.448819e+07  0.000575
24  1.259843e+08  3.451335  0.206435  ...  0.003347  1.259843e+08  0.000373
25  1.574803e+08  3.413125  0.205525  ...  0.003043  1.574803e+08  0.000284
26  1.889764e+08  3.370100  0.208610  ...  0.002896  1.889764e+08  0.000245
27  2.204724e+08  3.393215  0.208570  ...  0.002729  2.204724e+08  0.000213

[28 rows x 15 columns]

### Etapa 03:

Estimar a permeabilidade da torta

In [ ]:
def modelo_torta(kc,dados):

  # km = x[0]
  # kc = x[1]

  ps = dados[0]
  ec = dados[1]
  m = dados[2]
  n = dados[3]
  rho_fil = dados[4]
  const_c = dados[5]
  dP = dados[6]
  rm = dados[7]
  A = dados[8]
  V = dados[9]
  V0 = dados[10]
  dt_real = dados[11]

  # eqdarcy (dpl,mu)

  alpha = 1 / (ps*(1-ec)*kc)
  param_a = m*(1.1/(2.5*ec)**0.5 * 1/ kc**0.5)**(n-1)
  param_b = param_a*alpha*const_c*rho_fil / (A**(n+1)*dP)
  param_c = param_a * rm / (A**n * dP)
  param_d = 1/n

  dt_cal = ((param_c+V*param_b)**(param_d+1) - (param_c+V0*param_b)**(param_d+1)) / (param_b*(param_d+1))

  erro_rel = abs(dt_real-dt_cal) / dt_real

  return erro_rel

In [ ]:
dados_torta = pd.read_excel('parametros.xlsx',sheet_name='Test')
dados_torta['dt_real'] = dados_torta['t']-dados_torta['t0']
dados_torta

           yexp    m    n          xexp  ...        Rm   gx  meio  dt_real
0  3.149606e+07  0.8  0.3  4.255556e-07  ...  0.000004  0.4   120  1796.84

[1 rows x 17 columns]

In [ ]:
params_bound = [(1e-20,1e-10)]
# params_bound = [(1e-20,1e-10),(1,e-20,1e-10)]

results = []

for row in dados_torta.iterrows():
  dados_selecionados = [row[1]['ps'], 
                        row[1]['ec'], 
                        row[1]['m'], 
                        row[1]['n'], 
                        row[1]['rho_fil'], 
                        row[1]['Cs'],
                        row[1]['yexp'],
                        row[1]['Rm'],
                        row[1]['A'],
                        row[1]['V'],
                        row[1]['V0'],
                        row[1]['dt_real']]

  value = de(func=modelo_torta,bounds=params_bound,args=(dados_selecionados,))
  results.append(value)

df_torta = pd.DataFrame(results)
df_torta

                         x  fun  ...                                message  success
0  [5.817752631349319e-13]  1.0  ...  Optimization terminated successfully.     True

[1 rows x 6 columns]

In [ ]:
k_torta = []

for item in df_torta.x:
  k_torta.append(float(item))
  
dados_torta['k_torta'] = k_torta
dados_torta

           yexp    m    n          xexp  ...   gx  meio  dt_real       k_torta
0  3.149606e+07  0.8  0.3  4.255556e-07  ...  0.4   120  1796.84  5.817753e-13

[1 rows x 18 columns]